### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by onlyonewater** [google-research-datasets/Video-Timeline-Tags-ViTT#1]
Hi, in the annotations, where is the end time? I only see the start time.

**Comment by washingtonsk8** [comment]
@onlyonewater, according to the paper "annotators were asked to identify the main steps in a video and mark their start time." There is no mention to end times :'(

**Comment by gabrielhuang** [comment]
Hi all, sorry for the late answer.
We assume that the segments are contiguous, so each segment ends when the
next on starts.

**Comment by onlyonewater** [comment]
OK, I get it. Thanks!!!
